import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import AuthWrapper from "@/components/AuthWrapper";
import { Toaster } from "@/components/ui/sonner";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Stash",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="" lang="en">
      <body className={`${inter.variable} font-sans antialiased`}>
        <AuthWrapper>{children}</AuthWrapper>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
